language: cpp

compiler:
# ubuntu osg can't compile with clang http://forum.openscenegraph.org/viewtopic.php?t=10121
# - clang
 - gcc

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
  global:
    - ARCH_FLAGS_x86_64=''
    - secure: "todo"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
  - sudo apt-get update -qq
  - sudo apt-get purge cmake -qq
  - sudo apt-get install -qq cmake doxygen g++-4.9 libstdc++-4.9-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90
  - sudo apt-get install -qq libboost-all-dev libopenscenegraph-dev libqt4-dev

#install: true

before_script:
    - mkdir build
    - >
        eval "ARCH_FLAGS=\${ARCH_FLAGS_${ARCH}}" ;
        (cd build && cmake
        -DCMAKE_VERBOSE_MAKEFILE=ON
        -DCMAKE_BUILD_TYPE=$CONF
        -DCMAKE_CXX_FLAGS="$ARCH_FLAGS" ..)
script:
  - cd build
  - make
  - make doc
